- name: configuring shipping server 
  hosts: shipping
  become: yes 
  tasks:
  - name: install maven 
    ansible.builtin.package:
      name: maven 
      state: present 
  
  - name: installing PyMySQL
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3.9
  
  - name: create app directory 
    ansible.builtin.file:
      path: /app 
      state: directory 

  - name: create roboshop system user 
    ansible.builtin.user:
      name: roboshop 
      shell: /sbin/nologin
      system: true 
      home: /app 
  
  - name: download shipping code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip
  
  - name: extracting shipping code 
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes 
  
  - name: installing maven dependencies 
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app 
  
  - name: renaming shipping file 
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app 
  
  - name: copy shipping.service file 
    ansible.builtin.copy:
      src: shipping.service 
      dest: /etc/systemd/system/shipping.service

  - name: reload shipping 
    ansible.builtin.systemd_service:
      daemon_reload: true 

  - name: start and enable shipping 
    ansible.builtin.service:
      name: shipping 
      state: started 
      enabled: yes 

  - name: import data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.cloudwithmanoj.online
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping
   
  
  